# Site Settings
baseurl: ""
url : "https://etozzato.github.io"

# Blog Settings
theme_settings :
  title : E
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : E/TOZZATO
    description : makes pizza, writes computer code
    experience :
      - start : 1999
        end : 2003
        experience : HCS Studios, co-founder

      - start : 2000
        experience : Zopen.it, co-founder

      - start : 2001
        experience : Bonet Lepschy Associati, PHP programmer

      - start : 2004
        end : 2009
        experience : Venice International Photo Contest, co-founder

      - start : 2007
        end : 2008
        experience : MileyWorld, Ruby programmer

      - start : 2009
        experience : Sleepy Giant, Ruby programmer

      - start : 2010
        end : 2013
        experience : Sony Computer Entertainment of America, Ruby programmer

      - start : 2013
        end : 2017
        experience : FocusVision CORP, Ruby programmer

      - start : 2014
        experience : cookQ, co-founder

      - start : 2014
        end : 2018
        experience : PharmWare LIMS, co-founder

      - start : 2018
        experience : LabFlow LIMS, co-founder

    skills :
      - skill : RUBY, RAILS, JAVASCRIPT
        value : 96
      - skill : EMBERJS, FLUTTER, GO
        value : 64

  # Icons
  icons :
    email:  one@etozzato.com
    linkedin:  # Full URL
    github: etozzato
    gitlab:
    bitbucket:
    google_plus:
    twitter: mekdigital
    youtube:
    facebook:
    instagram: etozzato

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
